test:
  - src/GraphQL.Authorization.Tests/**/*
  - src/GraphQL.Authorization.ApiTests/**/*

CI:
  - .github/workflows/**/*
  - .github/dependabot.yml
  - .github/labeler.yml

code style:
  - .editorconfig

documentation:
  - README.md
